include $(FLMHOME)/flmtools.mk



EPOCROOT:=fred1
PLATFORM:=fred1
CFG:=fred1
TO_ROOT:=fred1
TO_BLDINF:=fred1
EPOCBLD:=fred1
EXTENSION_ROOT:=fred1
HOST_SHELL:=fred1
PLATFORM_PATH:=fred1
CFG_PATH:=fred1
TEMPLATE_EXTENSION_MAKEFILE:=temex.mk
HALPATH:=fred1/..

include $(FLMHOME)/template_ext.flm


EPOCROOT:=alice2
PLATFORM:=alice2
CFG:=alice2
TO_ROOT:=alice2
TO_BLDINF:=alice2
EPOCBLD:=alice2
EXTENSION_ROOT:=alice2
HOST_SHELL:=alice2
PLATFORM_PATH:=alice2
CFG_PATH:=alice2
TEMPLATE_EXTENSION_MAKEFILE:=temex.mk

include $(FLMHOME)/template_ext.flm


EPOCROOT:=test1
PLATFORM:=test2
CFG:=test3
TO_ROOT:=test4
TO_BLDINF:=test5
EPOCBLD:=test6
EXTENSION_ROOT:=test7
HOST_SHELL:=test8
PLATFORM_PATH:=test16
CFG_PATH:=test17
TEMPLATE_EXTENSION_MAKEFILE:=temex.mk

include $(FLMHOME)/template_ext.flm
