#!/bin/bash
#
# Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Contributors:
# Nokia Corporation - initial contribution.
#
# Description:
#  XSLT wrapper for Unix

BASEDIR=`dirname $0`

if [ $# != 0 ]
then
    exec java -jar $BASEDIR/xalanj/xalan.jar -xsl $0.xsl $@
fi

java -jar $BASEDIR/xalanj/xalan.jar -xsl $BASEDIR/lib/usage.xsl -in $0.xsl -param usage $0

