######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 22 10:31:36 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp
