#!/bin/bash
# Copyright (c) 2003-2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
# find out the directory of the script file
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)
python $SCRIPT_DIR/joinsysdef_mock.py $*
